name: build-docs
on: workflow_call
jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - run: npm install
            - run: node emu.js build
