name: build-docs
on: push
jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - name: load code
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - name: install dependencies
              run: npm install
            - name: build docs
              run: node emu.js build
            - name: deploy to pages
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages
                  folder: out
